name: dristi_open_source
description: "Open source app for Dristi 360"
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: 3.7.2
  flutter: "3.29.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_riverpod: 2.6.1
  logger: 2.5.0
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.17
  carousel_slider: 5.0.0
  equatable: 2.0.7
  dio: 5.8.0+1
  hive_flutter: 1.1.0
  flutter_localization: 0.3.1
  shimmer: 3.0.0
  go_router: 14.8.1
  cached_network_image: 3.4.1
  connectivity_plus: 6.1.3
  url_launcher: 6.3.1
  photo_view: 0.15.0
  flutter_staggered_grid_view: 0.7.0
  gal: 2.3.1
  in_app_review: 2.0.10
  package_info_plus: 8.3.0
  flutter_dotenv: 5.2.1
  share_plus: 10.1.4
  pub_semver: 2.2.0
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 7.0.0
  flutter_lints: 5.0.0

  # Run "flutter gen-l10n" if get Localization error

flutter:
  uses-material-design: true
  generate: true

  assets:
    - env/
    - assets/images/destination_items/
    - assets/images/travel_items/
    - assets/images/icons/
    - assets/images/items/
    - assets/images/social_media/
    - assets/images/destinations/
    - assets/json/

  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/Nova-Square-Regular.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Sans-Regular.ttf
          weight: 400
    - family: Vibes
      fonts:
        - asset: assets/fonts/Great-Vibes-Regular.ttf
          weight: 700

